#!/usr/bin/env bash
#
# Create .env with generated secrets, then report what still needs a human.
# Safe to re-run: an existing .env is never overwritten.

set -euo pipefail

cd "$(dirname "$0")/.."

if [ -f .env ]; then
  echo ".env already exists — leaving it alone."
  echo "Delete it first if you want a fresh one."
  exit 0
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl is required to generate secrets. Install it and re-run." >&2
  exit 1
fi

AUTH_SECRET="$(openssl rand -base64 32)"
POSTGRES_PASSWORD="$(openssl rand -hex 24)"

cat > .env <<EOF
# Generated by scripts/setup-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Keep this file out of version control — it is already in .gitignore.

# --- generated secrets -----------------------------------------------------
AUTH_SECRET="${AUTH_SECRET}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"

# --- public address --------------------------------------------------------
# For a local run, leave these as they are.
# To serve a real domain over HTTPS, set DOMAIN and ACME_EMAIL and start with
# the production overlay (see README).
AUTH_URL="http://localhost:3000"
NEXT_PUBLIC_BASE_URL="http://localhost:3000"
DOMAIN=""
ACME_EMAIL=""

# --- sign-in ---------------------------------------------------------------
# https://console.cloud.google.com/apis/credentials
# Authorized redirect URI: <your base URL>/api/auth/callback/google
AUTH_GOOGLE_ID=""
AUTH_GOOGLE_SECRET=""

# --- AI providers ----------------------------------------------------------
# Leave blank to run in mock mode: ffmpeg still renders, but the script and
# voice are placeholders.
OPENAI_API_KEY=""
FORCE_MOCK_PROVIDERS=""

# --- limits ----------------------------------------------------------------
MAX_UPLOAD_BYTES="2147483648"
MAX_SOURCE_SECONDS="14400"
RETENTION_DAYS="14"
WORKER_CONCURRENCY="2"
EOF

chmod 600 .env

cat <<'EOF'
Wrote .env with a generated AUTH_SECRET and database password.

Still needs you:
  AUTH_GOOGLE_ID / AUTH_GOOGLE_SECRET   sign-in (without these the login page
                                        says no provider is configured)
  OPENAI_API_KEY                        real transcripts, scripts, and voices
  DOMAIN / ACME_EMAIL                   only for the HTTPS production overlay

Then start it:
  docker compose up -d --build                      # http://localhost:3000
  docker compose -f docker-compose.yml \
                 -f docker-compose.prod.yml up -d --build   # https://$DOMAIN
EOF
